// app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Food Haven",
  description: "Generated by create next app",
};

function layout ({children}: {children: React.ReactNode}) {
    return ( 
        <html lang="en" className="bg-[#f5f8ff]">
        <body className={inter.className}>
          <div className="">
          <ToastContainer className="" />
                {children}
          </div>
        </body>
      </html>
    );
}

export default layout;