// app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar/Sidebar";
import Header from "@/components/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Food Haven",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex px-4">
          <Sidebar />
          <div className="flex-1 pl-0 md:pl-0 lg:pl-0">
            <Header />
            <div className="pt-16 px-4 mt-2 md:pl-64 lg:pl-64"> {/* Add padding top to accommodate header */}
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
