import "../src/styles/globals.css";
import { Metadata, Viewport } from "next";
import { Link } from "@nextui-org/link";
import clsx from "clsx";
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

import { Providers } from "./providers";

import Header from "@/src/components/Header";
import Footer from "@/src/components/Footer";
import BtnToTop from "@/src/components/BtnToTop";

import { StoreProvider } from "@/src/store/StoreProvider";

import { Analytics } from '@vercel/analytics/react';
import { SpeedInsights } from '@vercel/speed-insights/next';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "white" },
    { media: "(prefers-color-scheme: dark)", color: "black" },
  ],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StoreProvider>
    <html suppressHydrationWarning lang="en">
      <head />
      <body>
        <Providers themeProps={{ attribute: "class", defaultTheme: "light" }}>
         <Header />
         <ToastContainer className='mt-18'/>
         <BtnToTop />
              {children}
              <Analytics />
              <SpeedInsights />
           <Footer />
        </Providers>
      </body>
    </html>
    </StoreProvider>
  );
}
